-- 년,월,성별 별로 상품을 구매한 회원수
-- 년,월,성별 오름차순
-- 성별 정보가 없는 경우 제외
SELECT TO_CHAR(SALES_DATE,'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH, U.GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM USER_INFO U, ONLINE_SALE O
WHERE 1 = 1
AND U.USER_ID = O.USER_ID
AND U.GENDER IS NOT NULL
GROUP BY U.GENDER, TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE, 'MM')
ORDER BY  TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE, 'MM'), U.GENDER