-- 완료된 중고 거래의 총 금액이 70만워 이상
-- 회원, 닉네임, 총거래금액
-- 총거래금액 오름
SELECT U.USER_ID, U.NICKNAME ,SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE 1 = 1
AND B.WRITER_ID = U.USER_ID
AND B.STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(B.PRICE)