-- 대여 시작일 기준으로 2022년 8월부터 10월까지 총 대여횟수 5회 이상인 자동차
-- 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수
-- 월 오름차순, 자동차 내림차순, 특정 월의 대여 횟수가 0 이면 결과 제외
SELECT TO_NUMBER(TO_CHAR(A1.START_DATE, 'MM')) AS MONTH , A1.CAR_ID, COUNT(A1.CAR_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A1, (

SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE 1 = 1
   AND TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
 GROUP BY CAR_ID
 HAVING COUNT(CAR_ID) >= 5
      
      ) A2
 WHERE A1.CAR_ID = A2.CAR_ID
 AND TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
 GROUP BY TO_CHAR(A1.START_DATE, 'MM'), A1.CAR_ID
 HAVING COUNT(*) <> 0
 ORDER BY TO_CHAR(A1.START_DATE, 'MM') ASC , A1.CAR_ID DESC
 